p = peripheral.wrap("top")
local handle = assert(fs.open("disk/vars.txt", "r"), "Couldn't load var")
local input = handle.readAll()
handle.close()
local data = textutils.unserialize(input)

local function printfacture(player, pay)
p.newPage()
p.setPageTitle("facture de "..player)
p.setCursorPos(1,1)
p.write("electricité de extramods")
p.setCursorPos(1,2)
p.write("")
p.setCursorPos(1,3)
p.write("bonjour "..player..",")
p.setCursorPos(1,4)
p.write("il est l'heure de payer!")
p.setCursorPos(1,5)
p.write("")
p.setCursorPos(1,6)
p.write("------------------------")
p.setCursorPos(1,7)
p.write("total a payer TTC:")
p.setCursorPos(1,8)
p.write(pay.." emeraude")
p.setCursorPos(1,9)
p.write("------------------------")
p.setCursorPos(1,10)
p.write("les emeraude sont a")
p.setCursorPos(1,11)
p.write("donner  en main prope a")
p.setCursorPos(1,12)
p.write("louino")
p.setCursorPos(1,13)
p.write("------------------------")
p.setCursorPos(1,14)
p.write("si vous payez pas en")
p.setCursorPos(1,15)
p.write("temps et en heure, nous")
p.setCursorPos(1,16)
p.write("seront contraint de")
p.setCursorPos(1,17)
p.write("couper votre electricité.")
p.setCursorPos(1,18)
p.write("cordialement")
p.endPage()
end

if data.consolouloc ~= 0 then 
  printfacture("louloc", math.ceil(data.consolouloc*80))
end
if data.consororo ~= 0 then 
  printfacture("13roro_fermier", math.ceil(data.consororo*80))
end
if data.consoalexxpro ~= 0 then 
  printfacture("alexxpro", math.ceil(data.consoalexxpro*80))
end

p.newPage()
p.setPageTitle("compte rendu de J"..data.date.." à J"..os.day())
p.setCursorPos(1,1)
p.write("compte rendu de J"..data.date.." à J"..os.day())
p.setCursorPos(1,2)
p.write("")
p.setCursorPos(1,3)
p.write("13roro   --> "..math.ceil(data.consororo*80))
p.setCursorPos(1,4)
p.write("louloc   --> "..math.ceil(data.consolouloc*80))
p.setCursorPos(1,5)
p.write("louino   --> "..math.ceil(data.consolouino*80))
p.setCursorPos(1,6)
p.write("alexxpro --> "..math.ceil(data.consoalexxpro*80))
p.setCursorPos(1,7)
p.write("")
p.setCursorPos(1,8)
p.write("")
p.setCursorPos(1,9)
p.write("")
p.setCursorPos(1,10)
p.write("")
p.setCursorPos(1,11)
p.write("")
p.setCursorPos(1,12)
p.write("")
p.setCursorPos(1,13)
p.write("")
p.setCursorPos(1,14)
p.write("")
p.setCursorPos(1,15)
p.write("")
p.setCursorPos(1,16)
p.write("")
p.setCursorPos(1,17)
p.write("")
p.setCursorPos(1,18)
p.write("")
p.endPage()
