local pos = 0
local tem = 0.1
 
m = peripheral.wrap("left")
m.clear()
 
while true do
if pos==-316 then
pos = 82
end
m.clear()
m.setCursorPos(pos,1)
m.write("                                                                                                                                                     dddddddd                                                                                                                                                               ")
m.setCursorPos(pos,2)
m.write("                                               tttt                                                                                                  d::::::d                                                                                       tttt                                                                    ")
m.setCursorPos(pos, 3)
m.write("                                            ttt:::t                                                                                                  d::::::d                                                                                    ttt:::t                                                                    ")
m.setCursorPos(pos,4)
m.write("                                            t:::::t                                                                                                  d::::::d                                                                                    t:::::t                                                                    ")
m.setCursorPos(pos,5)
m.write("                                            t:::::t                                                                                                  d:::::d                                                                                     t:::::t                                                                    ")
m.setCursorPos(pos,6)
m.write("    eeeeeeeeeeee  xxxxxxx      xxxxxxxttttttt:::::ttttttt   rrrrr   rrrrrrrrr   aaaaaaaaaaaaa      mmmmmmm    mmmmmmm      ooooooooooo       ddddddddd:::::d     ssssssssss        nnnn  nnnnnnnn        eeeeeeeeeeee  xxxxxxx      xxxxxxxttttttt:::::ttttttt       ggggggggg   ggggg    eeeeeeeeeeee    nnnn  nnnnnnnn    ")
m.setCursorPos(pos,7)
m.write("  ee::::::::::::ee x:::::x    x:::::x t:::::::::::::::::t   r::::rrr:::::::::r  a::::::::::::a   mm:::::::m  m:::::::mm  oo:::::::::::oo   dd::::::::::::::d   ss::::::::::s       n:::nn::::::::nn    ee::::::::::::ee x:::::x    x:::::x t:::::::::::::::::t      g:::::::::ggg::::g  ee::::::::::::ee  n:::nn::::::::nn  ")
m.setCursorPos(pos,8)
m.write(" e::::::eeeee:::::eex:::::x  x:::::x  t:::::::::::::::::t   r:::::::::::::::::r aaaaaaaaa:::::a m::::::::::mm::::::::::mo:::::::::::::::o d::::::::::::::::d ss:::::::::::::s      n::::::::::::::nn  e::::::eeeee:::::eex:::::x  x:::::x  t:::::::::::::::::t     g:::::::::::::::::g e::::::eeeee:::::een::::::::::::::nn ")
m.setCursorPos(pos,9)
m.write("e::::::e     e:::::e x:::::xx:::::x   tttttt:::::::tttttt   rr::::::rrrrr::::::r         a::::a m::::::::::::::::::::::mo:::::ooooo:::::od:::::::ddddd:::::d s::::::ssss:::::s     nn:::::::::::::::ne::::::e     e:::::e x:::::xx:::::x   tttttt:::::::tttttt    g::::::ggggg::::::gge::::::e     e:::::enn:::::::::::::::n")
m.setCursorPos(pos,10)
m.write("e:::::::eeeee::::::e  x::::::::::x          t:::::t          r:::::r     r:::::r  aaaaaaa:::::a m:::::mmm::::::mmm:::::mo::::o     o::::od::::::d    d:::::d  s:::::s  ssssss        n:::::nnnn:::::ne:::::::eeeee::::::e  x::::::::::x          t:::::t          g:::::g     g:::::g e:::::::eeeee::::::e  n:::::nnnn:::::n")
m.setCursorPos(pos,11)
m.write("e:::::::::::::::::e    x::::::::x           t:::::t          r:::::r     rrrrrrraa::::::::::::a m::::m   m::::m   m::::mo::::o     o::::od:::::d     d:::::d    s::::::s             n::::n    n::::ne:::::::::::::::::e    x::::::::x           t:::::t          g:::::g     g:::::g e:::::::::::::::::e   n::::n    n::::n")
m.setCursorPos(pos,12)
m.write("e::::::eeeeeeeeeee     x::::::::x           t:::::t          r:::::r           a::::aaaa::::::a m::::m   m::::m   m::::mo::::o     o::::od:::::d     d:::::d       s::::::s          n::::n    n::::ne::::::eeeeeeeeeee     x::::::::x           t:::::t          g:::::g     g:::::g e::::::eeeeeeeeeee    n::::n    n::::n")
m.setCursorPos(pos,13)
m.write("e:::::::e             x::::::::::x          t:::::t    ttttttr:::::r          a::::a    a:::::a m::::m   m::::m   m::::mo::::o     o::::od:::::d     d:::::d ssssss   s:::::s        n::::n    n::::ne:::::::e             x::::::::::x          t:::::t    ttttttg::::::g    g:::::g e:::::::e             n::::n    n::::n")
m.setCursorPos(pos,14)
m.write("e::::::::e           x:::::xx:::::x         t::::::tttt:::::tr:::::r          a::::a    a:::::a m::::m   m::::m   m::::mo:::::ooooo:::::od::::::ddddd::::::dds:::::ssss::::::s       n::::n    n::::ne::::::::e           x:::::xx:::::x         t::::::tttt:::::tg:::::::ggggg:::::g e::::::::e            n::::n    n::::n")
m.setCursorPos(pos,15)
m.write(" e::::::::eeeeeeee  x:::::x  x:::::x        tt::::::::::::::tr:::::r          a:::::aaaa::::::a m::::m   m::::m   m::::mo:::::::::::::::o d:::::::::::::::::ds::::::::::::::s        n::::n    n::::n e::::::::eeeeeeee  x:::::x  x:::::x        tt::::::::::::::t g::::::::::::::::g  e::::::::eeeeeeee    n::::n    n::::n")
m.setCursorPos(pos,16)
m.write("  ee:::::::::::::e x:::::x    x:::::x         tt:::::::::::ttr:::::r           a::::::::::aa:::am::::m   m::::m   m::::m oo:::::::::::oo   d:::::::::ddd::::d s:::::::::::ss         n::::n    n::::n  ee:::::::::::::e x:::::x    x:::::x         tt:::::::::::tt  gg::::::::::::::g   ee:::::::::::::e    n::::n    n::::n")
m.setCursorPos(pos,17)
m.write("    eeeeeeeeeeeeeexxxxxxx      xxxxxxx          ttttttttttt  rrrrrrr            aaaaaaaaaa  aaaammmmmm   mmmmmm   mmmmmm   ooooooooooo      ddddddddd   ddddd  sssssssssss           nnnnnn    nnnnnn    eeeeeeeeeeeeeexxxxxxx      xxxxxxx          ttttttttttt      gggggggg::::::g     eeeeeeeeeeeeee    nnnnnn    nnnnnn")
m.setCursorPos(pos,18)
m.write("                                                                                                                                                                                                                                                                              g:::::g                                       ")
m.setCursorPos(pos,19)
m.write("                                                                                                                                                                                                                                                                  gggggg      g:::::g                                       ")
m.setCursorPos(pos,20)
m.write("                                                                                                                                                                                                                                                                  g:::::gg   gg:::::g                                       ")
m.setCursorPos(pos,21)
m.write("                                                                                                                                                                                                                                                                   g::::::ggg:::::::g                                       ")
m.setCursorPos(pos,22)
m.write("                                                                                                                                                                                                                                                                    gg:::::::::::::g                                        ")
m.setCursorPos(pos,23)
m.write("                                                                                                                                                                                                                                                                      ggg::::::ggg                                          ")
m.setCursorPos(pos,24)
m.write("                                                                                                                                                                                                                                                                         gggggg                                             ")

print(pos)
pos = pos-1
os.sleep(tem)
 end
